name: CI/CD Pipeline
on:
  push:
    branches: [main]
    tags:
      - '*'

env:
  REPO_NAME: my-first-docker-repo
  REGION: us-central1
  GKE_ZONE: us-central1-a
  IMAGE_REGISTRY: us-central1-docker.pkg.dev
  IMAGE_TAG: ${{ github.ref_type == 'tag' && github.ref_name || github.sha }}

permissions:
  contents: read
  id-token: write

jobs:
  build-push-deploy:
    environment: ${{ github.ref_type == 'tag' && 'prod' || 'dev' }}
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Application Code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ vars.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ vars.SERVICE_ACCOUNT }}

      - name: Configure Docker
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - name: Build and Push Images
        run: |
              docker build -t ${{ env.IMAGE_REGISTRY }}/${{ vars.PROJECT_ID }}/${{ env.REPO_NAME }}/backend:${{ env.IMAGE_TAG }} ./backend
              docker push ${{ env.IMAGE_REGISTRY }}/${{ vars.PROJECT_ID }}/${{ env.REPO_NAME }}/backend:${{ env.IMAGE_TAG }}

              docker build -t ${{ env.IMAGE_REGISTRY }}/${{ vars.PROJECT_ID }}/${{ env.REPO_NAME }}/frontend:${{ env.IMAGE_TAG }} ./frontend
              docker push ${{ env.IMAGE_REGISTRY }}/${{ vars.PROJECT_ID }}/${{ env.REPO_NAME }}/frontend:${{ env.IMAGE_TAG }}


      - name: Checkout Helm Chart
        uses: actions/checkout@v4
        with:
          repository: tusharguptaJ/DEVOPS-Tushar-UID00705-Devops-Assignment-Helm-Chart
          ref: main
          path: my-helm-chart

      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: ${{ vars.GKE_CLUSTER_NAME }}
          location: ${{ env.GKE_ZONE }}

      - name: Helm Deploy
        working-directory: ./my-helm-chart
        run: |          
          helm upgrade --install . -n induction-app --create-namespace \
          --set global.registry=${{ env.IMAGE_REGISTRY }} \
          --set backend-frontend.deployments.backend.container.image.repository=${{ vars.PROJECT_ID }}/${{ env.REPO_NAME }}/backend \
          --set backend-frontend.deployments.backend.container.image.tag=${{ env.IMAGE_TAG }} \
          --set backend-frontend.deployments.frontend.container.image.repository=${{ vars.PROJECT_ID }}/${{ env.REPO_NAME }}/frontend \
          --set backend-frontend.deployments.frontend.container.image.tag=${{ env.IMAGE_TAG }}
